name: domain url Parser from Wayback Machine

on:
  workflow_dispatch:  # This allows manual trigger from the GitHub UI.
    inputs:
        domain:
          description: 'domain url'
          required: false
          type: string

jobs:
  google_search:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install required Python dependencies
      run: |
        pip install DataRecorder aiohttp pandas python-dotenv httpx cloudflare

    - name: Run the Google search parser script
      run: |
        python main.py \
          --domain ${{ github.event.inputs.domain }} \

    - name: Commit the results to the repository if there's a change
      run: |
        git config --global user.name "GitHub Action"
        git config --global user.email "action@github.com"
      
        git add -A
        git commit -m "Add new Google search results"
        git push
