name: Run urls

on:
  workflow_dispatch:
    inputs:
      domain:
        description: 'Enter domain'
        required: true
        type: string
  # schedule:
  #   - cron: '0 0 */30 * *' # 每30天运行一次
  # push:
  #   branches:
  #     - main

jobs:
  search_volume:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          pip install DrissionPage aiohttp DataRecorder
          pip install python-dotenv

      - name: Create env file
        run: |
          echo "domain=${{ github.event.inputs.domain }}" > .env

      - name: Run Script
        run: |
          python main.py
