name: Submit apps

on:
  push:
    paths:
      - appstore.py
  workflow_dispatch:

jobs:
  scrape-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install aiohttp aiohttp_socks DataRecorder pandas

      - name: Run scraping script
        run: |
          python appstore.py

      - name: Create result archive
        run: |
          mkdir -p output
          tar -czf output/results.tar.gz result/

      - name: Create GitHub release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: v${{ github.run_number }}
          release_name: Scrape Results v${{ github.run_number }}
          draft: false
          prerelease: false

      - name: Upload results as release asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: output/results.tar.gz
          asset_name: results.tar.gz
          asset_content_type: application/gzip
